spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: b6bb768063205b3d090001f316b906c4
            client-secret: IjbAMP3VIBzATS99kM2qBdNkDHrNeqli
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            #http://localhost:8080/login/oauth2/code/kakao
#            redirect-uri: "http://localhost:3000/welcome"
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client-authentication-method: POST
            client-name: Kakao
          naver:
            client-id: xzs1rM1m8RcQK0Ac2VX2
            client-secret: Q3nF0242go
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response